#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "🤡❌🤡🤢 You have ONE job. 🤡❌🤡🤢
            Commit Message Failed. Can you just please follow the Conventional Commits?" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "❌🤡🤢🤮 Commit Message Too Long. ❌🤡🤢🤮
            You might as well spend it for your next essay when you are out of idea" >&2
    exit 1
fi

echo "The commit message looks great!"
